#server:
#  port: 8081
#  servlet:
#    context-path: /user-service
#
#spring:
#  application:
#    name: USER-SERVICE
#
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8081
  servlet:
    context-path: /user-service



